version: '3.8'

services:
  userservice:
    build: ./services/userservice
    ports:
      - "3000:3000"
    environment:
      - USER_MYSQL_HOST=mysql-cristiancaiza.alwaysdata.net
      - USER_MYSQL_USER=357693_cris
      - USER_MYSQL_PASSWORD=mysql123
      - USER_MYSQL_DBNAME=cristiancaiza_users

  client:
    build: ./client
    ports:
      - "3100:80"
