name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Build and push userservice Docker image to Docker Hub
    - name: Build and push userservice Docker image to Docker Hub
      run: |
        docker build -t antichrist667/userservice:latest ./services/userservice
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push antichrist667/userservice:latest

    # Deploy to Heroku using the Docker image
    - name: Deploy to Heroku
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
        docker tag antichrist667/userservice:latest registry.heroku.com/projectmanagement/web
        docker push registry.heroku.com/projectmanagement/web
        heroku container:release web --app projectmanagement
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
