name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Build and push userservice Docker image to Docker Hub
    - name: Build and push userservice Docker image to Docker Hub
      run: |
        docker build -t antichrist667/userservice:latest ./services/userservice
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push antichrist667/userservice:latest

    # Deploy userservice to Heroku using the Docker image
    - name: Deploy userservice to Heroku
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
        docker tag antichrist667/userservice:latest registry.heroku.com/userservice/web
        docker push registry.heroku.com/userservice/web
        heroku container:release web --app userservice
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # Build and push loginservice Docker image to Docker Hub
    - name: Build and push loginservice Docker image to Docker Hub
      run: |
        docker build -t antichrist667/loginservice:latest ./services/login
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push antichrist667/loginservice:latest

    # Deploy loginservice to Heroku using the Docker image
    - name: Deploy loginservice to Heroku
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
        docker tag antichrist667/loginservice:latest registry.heroku.com/loginservice/web
        docker push registry.heroku.com/loginservice/web
        heroku container:release web --app loginservice
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    # Build and push frontend Docker image to Docker Hub
    - name: Build and push frontend Docker image to Docker Hub
      run: |
        docker build -t antichrist667/frontend:latest ./frontend
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push antichrist667/frontend:latest

    # Deploy frontend to Heroku using the Docker image
    - name: Deploy frontend to Heroku
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
        docker tag antichrist667/frontend:latest registry.heroku.com/projectfrontend/web
        docker push registry.heroku.com/projectfrontend/web
        heroku container:release web --app projectfrontend
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
